// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	ForksCount  *int    `json:"forksCount"`
}

type Node struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	ForksCount  *int    `json:"forksCount"`
}

type Project struct {
	Node *Node `json:"node"`
}
